name: Copie README to Q1_archive_README

on:
  push:
    paths:
      - README.md  # Le workflow se déclenche uniquement si le fichier README.md est modifié

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Copy README.md to Q1_archive_README.md
        run: cp README.md Q1_archive_README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Q1_archive_README.md
          git commit -m "Add Q1_archive_README.md"
          git push
