name: Copier README dans Q1_archive_README

on:
  push:
    paths:
      - README.md  # Le workflow se déclenche uniquement si le fichier README.md est modifié

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Autorise l'écriture dans le dépôt
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Copier README.md vers archives/Q1_archive_README.md
        run: |
          mkdir -p archives
          cp README.md archives/Q1_archive_README.md

      - name: Ajouter et pousser les changements
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add archives/Q1_archive_README.md
          git commit -m "Ajout de archives/Q1_archive_README.md"
          git push origin HEAD
