name: Create Q2 Archive README

on:
  push:
    paths:
      - README.md  # Le workflow se déclenche uniquement si le fichier README.md est modifié

jobs:
  generate-archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Autorise l'écriture dans le dépôt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate archives/Q2_archive_README.md
        run: |
          mkdir -p archives
          echo "Nom et Prénom : LECOMTE Arthur" > archives/Q2_archive_README.md
          echo "Date et heure : $(date '+%d-%m-%Y %H:%M:%S')" >> archives/Q2_archive_README.md
          echo "" >> archives/Q2_archive_README.md
          cat README.md >> archives/Q2_archive_README.md

      - name: Ajouter et pousser les modifications
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add archives/Q2_archive_README.md
          git commit -m "Ajout archives/Q2_archive_README.md avec nom, date, et contenu du README"
          git push origin HEAD
