name: Archive Q3.java

on:
  push:
    paths:
      - Q3.java  # Le workflow se déclenche uniquement si le fichier Q3.java est modifié ou ajouté

jobs:
  archive-q3:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Autorise l'écriture dans le dépôt
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Créer Q3_archive_java.txt
        run: |
          echo "Nom et Prénom : LECOMTE Arthur" > Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt

      - name: Ajouter et pousser les changements
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Q3_archive_java.txt
          git commit -m "Ajout de Q3_archive_java.txt avec Q3.java et nom"
          git push origin HEAD
