name: Archive Q3.java

on:
  push:
    paths:
      - java/Q3.java  # Le workflow se déclenche uniquement si le fichier Q3.java est modifié ou ajouté

jobs:
  archive-q3:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Autorise l'écriture dans le dépôt
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Créer archives/Q3_archive_java.txt
        run: |
          mkdir -p archives
          echo "Nom et Prénom : LECOMTE Arthur" > archives/Q3_archive_java.txt
          echo "" >> archives/Q3_archive_java.txt
          cat java/Q3.java >> archives/Q3_archive_java.txt

      - name: Ajouter et pousser les changements
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add archives/Q3_archive_java.txt
          git commit -m "Ajout de archives/Q3_archive_java.txt avec Q3.java et nom"
          git push origin HEAD
