name: Archive Q6.java and Track Differences

on:
  push:
    paths:
      - java/Q6.java  # Le workflow se déclenche uniquement si le fichier Q6.java est modifié ou ajouté

jobs:
  archive-q6:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Autorise l'écriture dans le dépôt
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Créer un fichier archives/Q6_archive_date.txt avec des informations
        run: |
          mkdir -p archives
          DATE=$(date '+%d-%m-%Y-%H%M%S')  # Date au format JJ-MM-AAAA-HHMMSS
          FILENAME="archives/Q6_archive_${DATE}.txt"
          echo "Nom et Prénom : Arthur LECOMTE" > "$FILENAME"
          echo "" >> "$FILENAME"
          cat java/Q6.java >> "$FILENAME"
          echo "" >> "$FILENAME"
          echo "Taille (nombre de caractères) : $(wc -c < java/Q6.java)" >> "$FILENAME"
          echo "Nombre de lignes : $(wc -l < java/Q6.java)" >> "$FILENAME"
          echo "$FILENAME" > .current_filename.txt  # Stocker le nom pour l'utiliser plus tard

      - name: Comparer avec le fichier précédent
        run: |
          LATEST_FILE=$(ls -t archives/Q6_archive_*.txt 2>/dev/null | head -n 2 | tail -n 1)
          FILENAME=$(cat .current_filename.txt)
          echo "Fichier précédent : $LATEST_FILE"
          echo "Nouveau fichier : $FILENAME"

          if [ -z "$FILENAME" ] || [ ! -f "$FILENAME" ]; then
            echo "Erreur : Le nouveau fichier n'a pas été correctement créé." > archives/Q6_différences.txt
          elif [ -f "$LATEST_FILE" ]; then
            diff -u "$LATEST_FILE" "$FILENAME" > archives/Q6_différences.txt || true
          else
            echo "Aucune comparaison possible : aucun fichier précédent trouvé." > archives/Q6_différences.txt
          fi

      - name: Ajouter et pousser les fichiers
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add archives/Q6_archive_*.txt archives/Q6_différences.txt
          git commit -m "Ajout de archives/Q6_archive_DATE et Q6_différences.txt avec nom et infos"
          git push origin HEAD
