name: Archive Q6.java and Track Differences

on:
  push:
    paths:
      - Q6.java  # Le workflow se déclenche uniquement si Q6.java est modifié ou ajouté

jobs:
  archive-q6:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Autorise l'écriture dans le dépôt
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Créer un fichier Q6_archive_date.txt avec des informations
        run: |
          DATE=$(date '+%d-%m-%Y-%H%M%S')  # Date au format JJ-MM-AAAA-HHMMSS
          export FILENAME="Q6_archive_${DATE}.txt"  # Exporter pour usage ultérieur
          echo "Nom et Prénom : Arthur LECOMTE" > $FILENAME
          echo "" >> $FILENAME
          cat Q6.java >> $FILENAME
          echo "" >> $FILENAME
          echo "Taille (nombre de caractères) : $(wc -c < Q6.java)" >> $FILENAME
          echo "Nombre de lignes : $(wc -l < Q6.java)" >> $FILENAME
          echo "Fichier créé : $FILENAME"

      - name: Comparer avec le fichier précédent
        run: |
          # Identifier le fichier précédent
          LATEST_FILE=$(ls -t Q6_archive_*.txt 2>/dev/null | head -n 2 | tail -n 1)
          echo "Fichier précédent : $LATEST_FILE"
          echo "Nouveau fichier : $FILENAME"
          
          # Vérification de l'existence des fichiers
          if [ -z "$FILENAME" ]; then
            echo "Erreur : Le nouveau fichier n'a pas été correctement créé." > Q6_différences.txt
          elif [ -f "$LATEST_FILE" ]; then
            diff -u "$LATEST_FILE" "$FILENAME" > Q6_différences.txt || true
          else
            echo "Aucune comparaison possible : aucun fichier précédent trouvé." > Q6_différences.txt
          fi

      - name: Ajouter et pousser les fichiers
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Q6_archive_*.txt Q6_différences.txt
          git commit -m "Ajout de Q6_archive_DATE et Q6_différences.txt avec nom et infos"
          git push origin HEAD
